### ISSUE TITLE
ImportError: No module named colormath.color_conversions

### ISSUE THREAD

**Issue by nafis042** [gtaylor/python-colormath#80] opened 2017-10-25 11:05 UTC
I have a script which uses the following:
from colormath.color_conversions import convert_color

but when I run the script it shows me the error: 
ImportError: No module named colormath.color_conversions

the colormath version is 2.1.1

**Comment by VinceKumar** [comment] 2017-10-30 17:52
I think updating to 2.2 should fix your error 

```pip install git+git://github.com/gtaylor/python-colormath```

**Comment by andrelnunes** [comment] 2017-12-04 08:27
Still have the same problem.

from colormath.color_objects import sRGBColor, LabColor
ImportError: No module named colormath.color_objects

**Comment by KelSolaar** [comment] 2018-03-11 03:01
I could not reproduce with [3.0.0](https://github.com/gtaylor/python-colormath/tree/3.0.0), closing for now, feel free to add any comments.

**Closed by KelSolaar** 2018-03-11 03:01 UTC
